services:

  device:
    build:
      context: .
      args:
        SERVICE: device
    depends_on:
      - gateway
    environment:
      - GATEWAY_URL=http://gateway:8080

  gateway:
    build:
      context: .
      args:
        SERVICE: gateway
    depends_on:
      - nats
    ports:
      - "8080:8080"
    environment:
      - GATEWAY_ADDR=:8080
      - BROKER_URL=nats://nats:4222

  transformer:
    build:
      context: .
      args:
        SERVICE: transformer
    depends_on:
      - nats
    environment:
      - BROKER_URL=nats://nats:4222

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"

#   timescaledb:
#     image: timescale/timescaledb:latest-pg16
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: iot
#     volumes:
#       - iot-data:/var/lib/postgresql/data

# volumes:
#   iot-data:
